### ISSUE TITLE
add_index and add_constraint should default first arg to name

### ISSUE THREAD

**Issue by rabbiveesh** [nrdvana/perl-DBIx-Class-ResultDDL#5]
I think to match the rest of the API here, at the very least sugar should be provided for `add_index` (and `add_constraint`) so that instead of 

    add_index name => 'foo', fields => [ 'bar', 'baz' ]

You can write 

    add_index foo => fields => [ 'bar', 'baz' ]

Similar to the API for `unique`.

I've been using this feature in my code, and this is the minimum sugar I'd expect.

**Comment by nrdvana** [comment]
I sort of agree, though I don't know if the name is required/supported on all database backends.   I suppose if the name was not used, it would be ignored, and it isn't too much burden to ask developers to name their indexes...

But, you said you are using the add_index feature?  do you have any ideas how it could be made backward-compatible?  A name could be anything, and the list of fields in DBIC is free-form to allow for future extensions...

The other option is to make different sugar functions.

**Comment by nrdvana** [comment]
Actually, here is an idea.   If the first argument is a string which is not 'fields' and the second argument is an arrayref, it triggers a shortcut of ``add_index $name => [ @fields ]``.

An alternate is for ``idx`` to be the super-shorthand:

```
table 'foo';
col a => ...;
col b => ...;
idx IX_foo_a_b => [ 'a', 'b' ];
```

**Comment by rabbiveesh** [comment]
Yes, I am all over the idx string arrayref thing.

**Comment by rabbiveesh** [comment]
Don't bother with backwards compatibility for me, by the way. I don't mind
rewriting

**Comment by nrdvana** [comment]
How does this look?

``create_index`` sounds more DDL-ish than ``add_index``, and ``add_index`` was meant to be direct access to the SQL::Translator table method, so I renamed it to ``sqlt_add_index``, and then ``create_index`` has the nicer API.  And then I added ``idx`` as an alias for ``create_index``.

I've also pushed an unrelated but big change that allows us to write  ``col NAME => integer[];`` and similar array notations.

I also made a more aggressive back-compat strategy to make sure ``-V0`` doesn't change any behavior.

Can you check these changes on your project and see if it all works?

**Comment by rabbiveesh** [comment]
Be glad to. Would you mind doing a dev release on CPAN? Makes it easier to test

**Comment by nrdvana** [comment]
https://metacpan.org/pod/release/NERDVANA/DBIx-Class-ResultDDL-0.90_01/lib/DBIx/Class/ResultDDL.pm

and I'm noticing a lot of documentation that I need to fix, but the behavior is ready for testing.

**Comment by rabbiveesh** [comment]
@nrdvana I'm happy to tell you that my test suite is all green using the new sugar syntax! Looking forward to upgrading!
